/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    authors: Author;
    categories: Category;
    tags: Tag;
    media: Media;
    articles: Article;
    feeds: Feed;
    likes: Like;
    'ad-slots': AdSlot;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    feeds: FeedsSelect<false> | FeedsSelect<true>;
    likes: LikesSelect<false> | LikesSelect<true>;
    'ad-slots': AdSlotsSelect<false> | AdSlotsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'analytics-settings': AnalyticsSetting;
    robots: Robot;
    'site-settings': SiteSetting;
    'legal-page': LegalPage;
    'privacy-page': PrivacyPage;
    'cookies-page': CookiesPage;
    'contacts-page': ContactsPage;
  };
  globalsSelect: {
    'analytics-settings': AnalyticsSettingsSelect<false> | AnalyticsSettingsSelect<true>;
    robots: RobotsSelect<false> | RobotsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'legal-page': LegalPageSelect<false> | LegalPageSelect<true>;
    'privacy-page': PrivacyPageSelect<false> | PrivacyPageSelect<true>;
    'cookies-page': CookiesPageSelect<false> | CookiesPageSelect<true>;
    'contacts-page': ContactsPageSelect<false> | ContactsPageSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor' | 'author' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  bio?: string | null;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  showOnHome?: boolean | null;
  /**
   * Автоматически генерируется из названия. Используется в URL: /categories/slug
   */
  slug: string;
  /**
   * Автоматически генерируется: "НАЗВАНИЕ КАТЕГОРИИ - LADY.NEWS". Можно изменить вручную.
   */
  metaTitle?: string | null;
  /**
   * Автоматически генерируется: "Все материалы из категории НАЗВАНИЕ". Можно изменить вручную.
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Автоматически генерируется латиницей из названия. Используется в URL: /tags/slug
   */
  slug: string;
  /**
   * Автоматически генерируется: "НАЗВАНИЕ ТЕГА - LADY.NEWS". Можно изменить вручную.
   */
  metaTitle?: string | null;
  /**
   * Автоматически генерируется: "Все материалы по тегу НАЗВАНИЕ". Можно изменить вручную.
   */
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug?: string | null;
  status?: ('draft' | 'published') | null;
  publishedDate?: string | null;
  author: number | Author;
  coverImage?: (number | null) | Media;
  homeMainBlock?: boolean | null;
  homeTop?: boolean | null;
  homeMustRead?: boolean | null;
  /**
   * Если статья импортирована из фида, здесь хранится ссылка на исходное изображение.
   */
  feedImageUrl?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentHtml?: string | null;
  excerpt?: string | null;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    canonicalURL?: string | null;
  };
  /**
   * Если включено, статья не попадает в sitemap и может быть закрыта от индексации метатегами.
   */
  noindex?: boolean | null;
  /**
   * Количество просмотров статьи
   */
  viewCount: number;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feeds".
 */
export interface Feed {
  id: number;
  name: string;
  url: string;
  type?: ('rss' | 'json') | null;
  enabled?: boolean | null;
  /**
   * Человеческая заметка о расписании (например, * /30 * * * *). Фактический интервал задаётся в FEEDS_IMPORT_INTERVAL_MINUTES.
   */
  cron?: string | null;
  /**
   * Настройка соответствия полей фида полям статей
   */
  fieldMapping?: {
    /**
     * Имя поля в фиде для заголовка статьи (по умолчанию: title)
     */
    titleField?: string | null;
    /**
     * Имя поля в фиде для контента статьи (по умолчанию: content:encoded)
     */
    contentField?: string | null;
    /**
     * Имя поля в фиде для анонса статьи (по умолчанию: custom:secondTitle)
     */
    excerptField?: string | null;
    /**
     * Имя поля в фиде для автора статьи (по умолчанию: dc:creator или author)
     */
    authorField?: string | null;
    /**
     * Выберите источник автора для статей из этого фида
     */
    authorSource?: ('from_feed' | 'existing' | 'create_new') | null;
    /**
     * Автор, который будет назначен всем статьям из этого фида
     */
    existingAuthor?: (number | null) | Author;
    /**
     * Укажите имя, новый автор будет создан при первом импорте
     */
    newAuthorName?: string | null;
    /**
     * Имя поля в фиде для категории статьи. Если не указано или не найдено, будет использована категория с ID 64
     */
    categoryField?: string | null;
    /**
     * Имя поля в фиде для тегов статьи (по умолчанию: category)
     */
    tagsField?: string | null;
    /**
     * Имя поля в фиде для изображения статьи (по умолчанию: custom:image). Поддерживаются вложенные пути через точку, например: media:content.@_url
     */
    imageField?: string | null;
    /**
     * Имя поля в фиде для даты публикации (по умолчанию: pubDate)
     */
    dateField?: string | null;
    /**
     * ID категории, которая будет использоваться, если категория не указана в фиде
     */
    defaultCategoryId?: number | null;
  };
  lastImportedAt?: string | null;
  lastImportStatus?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "likes".
 */
export interface Like {
  id: number;
  article: number | Article;
  userHash: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-slots".
 */
export interface AdSlot {
  id: number;
  /**
   * Машинное имя слота (например, home_sidebar, article_sidebar). Используется на фронте.
   */
  key: string;
  label?: string | null;
  description?: string | null;
  enabled?: boolean | null;
  provider: 'yan' | 'adsense' | 'direct' | 'prebid';
  /**
   * Идентификатор блока РСЯ (blockId), без скрипта.
   */
  yandexBlockId?: string | null;
  /**
   * Значение атрибута data-ad-slot из кода AdSense.
   */
  adsenseSlotId?: string | null;
  adFormat?: string | null;
  width?: number | null;
  height?: number | null;
  /**
   * Подсказка для разработчиков: показывает пример кода компонента AdSlot, который рендерит этот слот.
   */
  usageHint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'feeds';
        value: number | Feed;
      } | null)
    | ({
        relationTo: 'likes';
        value: number | Like;
      } | null)
    | ({
        relationTo: 'ad-slots';
        value: number | AdSlot;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  showOnHome?: T;
  slug?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedDate?: T;
  author?: T;
  coverImage?: T;
  homeMainBlock?: T;
  homeTop?: T;
  homeMustRead?: T;
  feedImageUrl?: T;
  content?: T;
  contentHtml?: T;
  excerpt?: T;
  categories?: T;
  tags?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalURL?: T;
      };
  noindex?: T;
  viewCount?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feeds_select".
 */
export interface FeedsSelect<T extends boolean = true> {
  name?: T;
  url?: T;
  type?: T;
  enabled?: T;
  cron?: T;
  fieldMapping?:
    | T
    | {
        titleField?: T;
        contentField?: T;
        excerptField?: T;
        authorField?: T;
        authorSource?: T;
        existingAuthor?: T;
        newAuthorName?: T;
        categoryField?: T;
        tagsField?: T;
        imageField?: T;
        dateField?: T;
        defaultCategoryId?: T;
      };
  lastImportedAt?: T;
  lastImportStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "likes_select".
 */
export interface LikesSelect<T extends boolean = true> {
  article?: T;
  userHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ad-slots_select".
 */
export interface AdSlotsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  description?: T;
  enabled?: T;
  provider?: T;
  yandexBlockId?: T;
  adsenseSlotId?: T;
  adFormat?: T;
  width?: T;
  height?: T;
  usageHint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Подключение Яндекс.Метрики, Google Analytics и кодов верификации для Google/Yandex Webmaster.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings".
 */
export interface AnalyticsSetting {
  id: number;
  /**
   * Настройки счётчика Яндекс.Метрики. Вставка кода происходит автоматически на всех страницах.
   */
  yandexMetrica?: {
    enabled?: boolean | null;
    /**
     * Числовой ID счётчика, например 12345678.
     */
    counterId?: string | null;
  };
  /**
   * Настройки Google Analytics 4 (gtag). Скрипт подключается на всех страницах.
   */
  googleAnalytics?: {
    enabled?: boolean | null;
    /**
     * Идентификатор вида G-XXXXXXX.
     */
    measurementId?: string | null;
  };
  /**
   * Коды верификации для Google Search Console и Яндекс.Вебмастер. Будут добавлены как meta-теги на всех страницах.
   */
  webmaster?: {
    /**
     * Значение атрибута content из meta name="google-site-verification" (только сам код, без тега).
     */
    googleVerification?: string | null;
    /**
     * Значение атрибута content из meta name="yandex-verification" (только сам код, без тега).
     */
    yandexVerification?: string | null;
  };
  /**
   * Содержимое будет вставлено как есть внутрь <head> на всех страницах. Используйте только доверенный код (пиксели, скрипты, мета-теги).
   */
  customHeadHtml?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Содержимое файла robots.txt, который отдаётся на фронте по /robots.txt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "robots".
 */
export interface Robot {
  id: number;
  /**
   * Полный текст файла robots.txt. Если оставить пустым, будет использован дефолт (Allow: / + Sitemap).
   */
  content?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Текущий язык сайта (RU/EN) и переводы заголовков блоков и футера.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  currentLanguage: 'ru' | 'en';
  /**
   * Используется как текстовый логотип в шапке и футере.
   */
  siteName?: string | null;
  /**
   * Произвольный CSS, который будет добавлен в <head> внутри <style>. Можно использовать, чтобы переопределить стили .site-logo-header.
   */
  headerLogoCss?: string | null;
  /**
   * Необязательный текст под логотипом в шапке, например: NEWS ABOUT MODA.
   */
  headerTagline?: string | null;
  labels?: {
    homeMainRu?: string | null;
    homeMainEn?: string | null;
    homeLatestRu?: string | null;
    homeLatestEn?: string | null;
    homeMustReadRu?: string | null;
    homeMustReadEn?: string | null;
    homePopularRu?: string | null;
    homePopularEn?: string | null;
    homeTagsRu?: string | null;
    homeTagsEn?: string | null;
    articleReadMoreRu?: string | null;
    articleReadMoreEn?: string | null;
    articleAlsoOnTopicRu?: string | null;
    articleAlsoOnTopicEn?: string | null;
  };
  seo?: {
    homeTitleEn?: string | null;
    homeTitleRu?: string | null;
    homeDescriptionEn?: string | null;
    homeDescriptionRu?: string | null;
    categoryTitleSuffixEn?: string | null;
    categoryTitleSuffixRu?: string | null;
    categoryDescriptionTemplateEn?: string | null;
    categoryDescriptionTemplateRu?: string | null;
    tagTitleSuffixEn?: string | null;
    tagTitleSuffixRu?: string | null;
    tagDescriptionTemplateEn?: string | null;
    tagDescriptionTemplateRu?: string | null;
    searchTitleTemplateEn?: string | null;
    searchTitleTemplateRu?: string | null;
    searchDescriptionTemplateEn?: string | null;
    searchDescriptionTemplateRu?: string | null;
    articleReadMoreEn?: string | null;
    articleReadMoreRu?: string | null;
  };
  footer?: {
    textRu?: string | null;
    textEn?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Контент страницы «Правовая информация» (RU/EN), отображаемой по адресу /legal/.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-page".
 */
export interface LegalPage {
  id: number;
  /**
   * HTML для русской версии страницы /legal/.
   */
  contentRu?: string | null;
  /**
   * HTML для английской версии страницы /legal/.
   */
  contentEn?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Контент страницы «Политика конфиденциальности» (RU/EN), отображаемой по адресу /privacy-policy/.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page".
 */
export interface PrivacyPage {
  id: number;
  /**
   * HTML для русской версии страницы /privacy-policy/.
   */
  contentRu?: string | null;
  /**
   * HTML для английской версии страницы /privacy-policy/.
   */
  contentEn?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Контент страницы «Политика использования файлов Cookie» (RU/EN), отображаемой по адресу /cookies-policy/.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookies-page".
 */
export interface CookiesPage {
  id: number;
  /**
   * HTML для русской версии страницы /cookies-policy/.
   */
  contentRu?: string | null;
  /**
   * HTML для английской версии страницы /cookies-policy/.
   */
  contentEn?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Контент страницы «Контакты» (RU/EN), отображаемой по адресу /contacts/.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page".
 */
export interface ContactsPage {
  id: number;
  /**
   * HTML для русской версии страницы /contacts/.
   */
  contentRu?: string | null;
  /**
   * HTML для английской версии страницы /contacts/.
   */
  contentEn?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings_select".
 */
export interface AnalyticsSettingsSelect<T extends boolean = true> {
  yandexMetrica?:
    | T
    | {
        enabled?: T;
        counterId?: T;
      };
  googleAnalytics?:
    | T
    | {
        enabled?: T;
        measurementId?: T;
      };
  webmaster?:
    | T
    | {
        googleVerification?: T;
        yandexVerification?: T;
      };
  customHeadHtml?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "robots_select".
 */
export interface RobotsSelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  currentLanguage?: T;
  siteName?: T;
  headerLogoCss?: T;
  headerTagline?: T;
  labels?:
    | T
    | {
        homeMainRu?: T;
        homeMainEn?: T;
        homeLatestRu?: T;
        homeLatestEn?: T;
        homeMustReadRu?: T;
        homeMustReadEn?: T;
        homePopularRu?: T;
        homePopularEn?: T;
        homeTagsRu?: T;
        homeTagsEn?: T;
        articleReadMoreRu?: T;
        articleReadMoreEn?: T;
        articleAlsoOnTopicRu?: T;
        articleAlsoOnTopicEn?: T;
      };
  footer?:
    | T
    | {
        textRu?: T;
        textEn?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-page_select".
 */
export interface LegalPageSelect<T extends boolean = true> {
  contentRu?: T;
  contentEn?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page_select".
 */
export interface PrivacyPageSelect<T extends boolean = true> {
  contentRu?: T;
  contentEn?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookies-page_select".
 */
export interface CookiesPageSelect<T extends boolean = true> {
  contentRu?: T;
  contentEn?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page_select".
 */
export interface ContactsPageSelect<T extends boolean = true> {
  contentRu?: T;
  contentEn?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}