---
webapp_root: "/opt/webapp"
webapp_group: "webapp"
webapp_repo_url: "git@github.com:bratkovskiy/newsportal.git"
webapp_repo_branch: "main"
webapp_repo_dest: "{{ webapp_root }}/app"
webapp_web_dir: "{{ webapp_repo_dest }}/apps/web"
webapp_cms_dir: "{{ webapp_repo_dest }}/apps/cms"
webapp_deploy_user: "{{ ansible_user | default('deploy') }}"
webapp_git_deploy_key_local: "{{ lookup('env', 'ANSIBLE_SSH_KEY') | default(lookup('env', 'HOME') + '/.ssh/id_ed25519', true) }}"
webapp_git_deploy_key_remote: "/home/{{ webapp_deploy_user }}/.ssh/id_ed25519_deploy"

service_user_web: "web"
service_user_cms: "cms"

webapp_env_dir: "/etc/webapp"
webapp_vault_mount: "webapp"
webapp_vault_secret_path: "env"
webapp_web_env_field: "web_env"
webapp_cms_env_field: "cms_env"

# Tailscale
tailscale_authkey: "{{ lookup('env', 'TAILSCALE_AUTHKEY') | default('') }}"
webapp_web_env_file: "{{ webapp_env_dir }}/web.env"
webapp_cms_env_file: "{{ webapp_env_dir }}/cms.env"

astro_service_name: "astro-frontend"
cms_service_name: "payload-backend"
astro_port: 4000
cms_port: 3000

vault_addr: "{{ lookup('env', 'VAULT_ADDR') }}"
vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
vault_skip_verify: "{{ lookup('env', 'VAULT_SKIP_VERIFY') | default('true') }}"

nodejs_version: "20"

nginx_cache_path: "/var/cache/nginx"

postgres_packages:
  - postgresql
  - postgresql-contrib
  - python3-psycopg2
postgres_user: "payload"
postgres_password: "password"
postgres_db_name: "payload"

cms_media_dir: "{{ webapp_cms_dir }}/src/media"
